### ISSUE TITLE
undefined symbol: ev_default_loop_ptr

### ISSUE THREAD

**Issue by brzpegasus** [creationix/node-sdl#15]
I followed all the instructions up to, and including, the node-waf configure build step. The messages all suggest a successful build, but when I run any of the examples, e.g. `node img.js`, I get the following error:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/edeblois/Projects/node-sdl/build/Release/node-sdl.node: undefined symbol: ev_default_loop_ptr
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/edeblois/Projects/node-sdl/sdl.js:1:90)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Any idea why that error would occur? I googled a bit and saw a post that says native modules need to be rebuilt with newer compiled versions of node. Not really sure what that means. I'm running node 0.10.0, but have tried using earlier versions and re-ran node-waf. There was no change. Was hoping someone could steer me in the right direction =).

I'm running this on Linux Mint 14, if that makes any difference.

**Comment by Freezerburn** [comment]
This issue is outdated. ev_default_loop_ptr does not exist in newer versions of node. I removed the code that used the old node event loop.
