### ISSUE TITLE
Not finding SDL_ttf.h on MacOS 10.8

### ISSUE THREAD

**Issue by jlopezr** [creationix/node-sdl#16]
Trying to compile it from git on mac gives problems to find the SDL_ttf.h. It exists and it's located on /opt/local/include/SDL/SDL_ttf.h, the same directory where the rest of SDL includes (macports default).

8<--------------------------------------------------------------------------
juan@MacBook-Pro-de-Juan:~/Dropbox/Proyectos/ARDrone/NodeCopter/node-sdl$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.6
gyp info using node@0.11.2 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/opt/local/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/juan/Dropbox/Proyectos/ARDrone/NodeCopter/node-sdl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/juan/.node-gyp/0.11.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/juan/.node-gyp/0.11.2',
gyp info spawn args   '-Dmodule_root_dir=/Users/juan/Dropbox/Proyectos/ARDrone/NodeCopter/node-sdl',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
juan@MacBook-Pro-de-Juan:~/Dropbox/Proyectos/ARDrone/NodeCopter/node-sdl$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.6
gyp info using node@0.11.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/libnode-sdl/src/helpers.o
In file included from ../src/helpers.cc:4:
../src/SDL.h:7:10: fatal error: 'SDL_ttf.h' file not found
# include <SDL_ttf.h>

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/libnode-sdl/src/helpers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/opt/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/juan/Dropbox/Proyectos/ARDrone/NodeCopter/node-sdl
gyp ERR! node -v v0.11.2
gyp ERR! node-gyp -v v0.9.6
gyp ERR! not ok

**Comment by TheKnarf** [comment]
If you have homebrew installed:

`brew install sdl2_ttf`
